### ISSUE TITLE
Virtual Tour

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#1]
This content needs to be gathered/created for the website.

**Comment by kennygrosz** [comment]
these videos exist on youtube. we can ask past O-Week coords for them, or ask the current coords to make new ones over the summer

**Comment by pjgranahan** [comment]
@kennygrosz Do you know where to look? Does Hanszen have a dedicated Youtube channel or something like that?

**Comment by kennygrosz** [comment]
they aren't glamorous but here are the videos:
New Section:  https://www.youtube.com/watch?v=DIthbnvCRJ8 
Old section:  https://www.youtube.com/watch?v=RjlHcBbOurI

**Comment by pjgranahan** [comment]
Added
