### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#10]
This content needs to be gathered/created for the website.
- [x] H-Team
- [x] Executive cabinet
- [x] Committees

**Comment by nikliebster** [comment]
Do we have some profiles archived somewhere, or should I just email the H-Team and Exec Cab to ask them to submit short bios?

**Comment by kennygrosz** [comment]
@nikliebster There are probably bios of the H-Team in your O-Week Book. I would ask the H-Team if they want you to just use those, and then they will either send you a new one or you can ask the O-Week Coords (read: Trenton) for the electronic copy.

**Comment by pjgranahan** [comment]
Thanks @nikliebster. As far as I know, there are no archived profiles, and there's some question as to how valuable it really is to have bios for exec cab members. I would say email the H-Team asking for maybe a photo and a bio that they would like featured on the website. As for exec cab and committees, I think those profiles should be more focused on the position rather than the current position holder. Any other thoughts? @hanszen/website

**Comment by nikliebster** [comment]
In that case, I feel like the H-Team should have a page of profiles, and History and Cabinet structure could maybe be combined. That seems to fit together better to me, seeing as it divides positions from actual people. What do you think? Just brainstorming.

**Comment by kennygrosz** [comment]
I think Hanszen History and Cabinet should be different things:

History including: who is Harry Hanszen, when was the college conceived, what is the Gentleman's / Family College,  traditions, innovation (coffee house, etc.)

Cabinet = How the college is currently run (and I think should include at least the names and contact info for different cabinet positions)

**Comment by vxd1** [comment]
We could always combine the Constitution and Cabinet on a single page, too. Just have the constitution added as a link

I also agree with Kenny ^^

**Comment by kennygrosz** [comment]
^ to that end, I think constitution should be a separate link and easily accessible since a lot of people use the website just to get to that

**Comment by vxd1** [comment]
Could it be condensed with Forms/Files? Like all the space requests, etc with the Constitution?

**Comment by pjgranahan** [comment]
This is really valuable discussion on an important topic. I made a separate issue so we can focus on just the structure of the content on the website: #16

**Comment by nikliebster** [comment]
Here's a compiled list of Exec Cab. We're switching things up a bit, so not sure where this goes. I'll put it here for now.

President: Kenny Groszman
Email: kg16@rice.edu
Phone: (561) 445-0491

CJ: Andrew Elsey
Email: ase1@rice.edu
Phone: (727) 432-0804

IVP: Jack Toups
Email: jdt6@rice.edu
Phone: (281) 788-8274

EVP: Ben Baldazo
Email: bjb10@rice.edu
Phone: (512) 966-9587

Treasurers: 
Henry Lanear
Email: hl3@rice.edu
Phone: (816) 824-6597

Brian Walker
Email: bkw4@rice.edu
Phone: (206) 459-4342

Secretaries:
Nik Liebster
Email: ndl1@rice.edu
Phone: (713) 382-4989

Gillian Mellor:
Email: grm5@rice.edu
Phone: (512) 903-6771

**Comment by pjgranahan** [comment]
Added
