### ISSUE TITLE
Wiki FAQs

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#11]
This content needs to be gathered/created for the website.

[FAQ page](https://github.com/hanszen/hanszen.github.io/wiki/FAQ#faq)
- [x] How to send a listserv email
- [ ] How to update the website
- [ ] How to send an announcement to all of Hanszen

**Comment by kennygrosz** [comment]
how to send a listserv email:
Send your email to hanszen@mailman.rice.edu

You can only send your email through an email address that's registered on the listserv.

By default, this email will be the one that is of the form:
FirstName.MiddleInitial.LastName@rice.edu, which you should be able to access by signing into gmail as netID@rice.edu. 

If you prefer to have a different email address on the listserv, you can make it happen by getting in touch with the college coordinator

**Comment by pjgranahan** [comment]
@kennygrosz can you add that directly to the Wiki: https://github.com/hanszen/hanszen.github.io/wiki/FAQ#faq

**Comment by kennygrosz** [comment]
donezo

**Comment by pjgranahan** [comment]
@kennygrosz Can you add a blurb about how and when to send an announcement to the secretaries? That's what I was aiming for in https://github.com/hanszen/hanszen.github.io/wiki/FAQ#how-do-i-send-an-announcement-to-all-of-hanszen

**Comment by kennygrosz** [comment]
do you mean like to the secretaries of all the colleges? there's a listserv called **REDACTED** but I don't think it should be published because it's already abused enough. thoughts? @nikliebster

**Comment by nikliebster** [comment]
I'm with Kenny. We don't need more emails being sent to **REDACTED**, and besides, almost everything that is related to Hanszen is more appropriate for HFH.

**Comment by pjgranahan** [comment]
Whatever y'all think is best. Is it proper listserv etiquette then to email [HFH] if it is specifically Hanszen related, and [**REDACTED**] if it's university related, which will then be passed on by each college's secretaries? I think this is a good place to detail whatever the proper etiquette is.

**Comment by kennygrosz** [comment]
I think the concern is that [**REDACTED**] is open to the public and could easily be abused if anyone bad found out about it and it started getting spammed, so we don't wanna put that on the website.

We could say, "if you need to send an email to the whole university, get in touch with the secretaries and they can tell you more"

**Comment by pjgranahan** [comment]
In the spirit of keeping that listserv more private, I've gone through our comments and redacted any named mentions of it.

**Comment by kennygrosz** [comment]
Hi,

the [HFH] listserv is fine if it's on there (potentially unnecessary but
fine) since you have to be on the listserv to post on it.

-Kenny

On Wed, Apr 20, 2016 at 11:09 PM, Patrick Granahan <notifications@github.com

**Comment by pjgranahan** [comment]
Opted to remove the wiki for the time being, in favor of releasing earlier
