### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#14]
Add a mechanism to collect feedback on the website.

**Comment by ase1** [comment]
Would it be easiest to make a google form for this?

**Comment by pjgranahan** [comment]
This is non-blocking, I'm removing it from the beta milestone.

@ase1 Either google forms or have people raise issues on Github (I'd prefer this one). Or collect feedback manually

**Comment by pjgranahan** [comment]
Implemented
