### ISSUE TITLE
Website structure

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#16]
Brainstorm here about how the website should be structured @hanszen/website 

My initial thoughts were something along this line:
- Home Page
  - Calendar
  - Important announcements
- About
  - History
  - Traditions
  - Government
- People
  - H-Team
    - Coordinator
    - Masters
    - RAs
  - Fellows
    - ?
- O-Week
  - Sub-website, dedicated to O-Week concerns?
- Contact
  - Hanszen's Address
  - H-Team contact info
  - How to send an announcement to the secretaries

**Comment by nikliebster** [comment]
To update where the last conversation left off:
Descriptions of cabinet positions is going under the "Government" section.
Bios/blurbs about H-Team go under "People", as well as maybe contact information for executive cabinet members, as @kennygrosz  suggested. 
Is this correct so far?

**Comment by kennygrosz** [comment]
Thoughts:
- Home Page
  - Calendar
  - Important announcements 
- About Hanszen
  - History
  - Traditions
  - Spaces (include pictures of buildings, commons, etc.)
- Government
  - Cabinet
    - Executive Cabinet (names and info)
      - Class reps and other positions
  - Committees
    - Standing Committees (information and contact information for committee heads)
    - Initiative committees
       -info and committee heads
      - past initiative committees (so we can have institutional memory about this)
    - Constitution, Bylaws, Judicial Code, Election Code
- People (or maybe Resources??)
  - H-Team
    - Coordinator
    - Masters
    - RAs
  - Fellows
  - PAA's
  - RHA's 
  - STRIVE Liaisons
- O-Week
      - Sub-website, dedicated to O-Week concerns?
- Contact
  - Hanszen's Address
  - H-Team contact info
  - How to send an announcement to the secretaries

Honestly, not really sure... But all of this stuff needs to be there in some capacity. I think a lot of it we can borrow or adapt from O-Week Books

**Comment by nikliebster** [comment]
I like using "Resources" instead of "People." Should H-Team be incorporated in "government" somehow, as college leadership?

**Comment by kennygrosz** [comment]
I like that^

**Comment by pjgranahan** [comment]
Mostly set up at this point
