### ISSUE TITLE
Landing page blurb

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#17]
The landing page (http://hanszen.github.io/ for now) has a great spot for a brief blurb about Hanszen that I think the president should write.

It might say something like "Welcome to Hanszen, the best college at Rice, enjoy our website" or something that is also semi-targeted at the incoming freshmen.

Thoughts?

**Comment by kennygrosz** [comment]
Hanszen is one of Rice University's oldest residential colleges and objectively its greatest. If you're a Hanszenite past, present, or future, welcome to the online hearth of our Hanszen family! If you're not a Hanszenite, my sincerest condolences. 

Regardless, feel free to take a look around our brand new website and see what we are up to! 

Kenny Groszman
Hanszen President 2016-2017
