### ISSUE TITLE
Room floor plans

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#2]
This content needs to be gathered/created for the website.

**Comment by kennygrosz** [comment]
Asking Joyce for info

**Comment by kennygrosz** [comment]
![new section floor plan](https://cloud.githubusercontent.com/assets/11845671/15201331/96e311ce-17b5-11e6-8336-e58add73dbf1.png)
![old section double floor plan](https://cloud.githubusercontent.com/assets/11845671/15201332/96e3db72-17b5-11e6-929a-7a146071e19f.png)
![old section quad floor plan](https://cloud.githubusercontent.com/assets/11845671/15201333/96ee0fde-17b5-11e6-840e-f7a5733a202a.png)

text from O-Week book that is probably useful:

*Room dimensions are averages-- individual rooms may vary

All rooms contain the following:
- extra-long twin bed
- either a walk-in closet or a standing wardrobe
- dresser
- desk and desk chair
- trash can and recycling bin
- book shelves
- Ethernet port
- TV cable and telephone jack (one per room)

Old Section Double: The Old Section Double is what most people imagine when they think of a stereotypical “college room.” Depending on how much stuff the two people inside it have, doubles can range from spacious to cozy, but don’t worry: there is plenty of space for the creative mind.

Old Section Quad: An Old Section Quad is basically two doubles with a door connecting them. Many students choose to treat the quads this way, with two beds in each room, although many also choose to put all four beds in the inner room and have the outer room as a living room.

New Section Quad: New Section Quads are two doubles that share a common room. Two New Section Quads share a bathroom in the middle that connect the two.

**Comment by pjgranahan** [comment]
Added
