### ISSUE TITLE
Photo Gallery

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#4]
This content needs to be gathered/created for the website.
- [ ] Traditions (Beer Bike, Crane Day, Cascarones, etc.)
- [ ] Spaces (new music room, commons, etc.)
- [ ] Smiling people

**Comment by jjbean97** [comment]
I can look through hanszen history and email it them to you, or do you want it posted in these comments? @pjgranahan

**Comment by pjgranahan** [comment]
@jjbean97  if you maybe pick out some pics for each category that you are high quality, and just categorize and post the facebook URLs here, I can grab them when I go to put up those pages.

**Comment by jjbean97** [comment]
TRADITIONS
-Beer Bike https://www.facebook.com/hanszenhistory/photos/a.473361306109266.1073741842.399814146797316/823074137804646/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.819349868177073.1073741894.399814146797316/819398121505581/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.819349868177073.1073741894.399814146797316/819351528176907/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.819349868177073.1073741894.399814146797316/819350278177032/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.818425211602872.1073741892.399814146797316/818425258269534/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.818424648269595.1073741891.399814146797316/818424861602907/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.818429858269074.1073741893.399814146797316/818430501602343/?type=3&theater
https://www.facebook.com/photo.php?fbid=828753650580439&set=g.365966220084053&type=1&theater

-Mr. Hanszen
https://www.facebook.com/hanszenhistory/photos/a.818425211602872.1073741892.399814146797316/818427948269265/?type=3&theater

-Crane Day
https://www.facebook.com/photo.php?fbid=986185118128431&set=p.986185118128431&type=3&theater
https://www.facebook.com/photo.php?fbid=986163791463897&set=p.986163791463897&type=3&theater
https://www.facebook.com/photo.php?fbid=986302908116652&set=gm.1535277123438844&type=3&theater

-Porker
https://www.facebook.com/hanszenhistory/photos/a.752451331533594.1073741884.399814146797316/752452118200182/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.752451331533594.1073741884.399814146797316/752452864866774/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.752451331533594.1073741884.399814146797316/752451604866900/?type=3&theater

-Cascarones
https://www.facebook.com/hanszenhistory/photos/a.503299509782112.1073741849.399814146797316/503311213114275/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.503299509782112.1073741849.399814146797316/503311443114252/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.503299509782112.1073741849.399814146797316/503299779782085/?type=3&theater

-Civil War
https://www.facebook.com/hanszenhistory/photos/a.742674952511232.1073741881.399814146797316/742678042510923/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.742674952511232.1073741881.399814146797316/742677052511022/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.742674952511232.1073741881.399814146797316/742675479177846/?type=3&theater

-Christmas
https://www.facebook.com/hanszenhistory/photos/a.742295825882478.1073741880.399814146797316/775233299255397/?type=3&theater

SMILING PEOPLE
https://www.facebook.com/hanszenhistory/photos/pb.399814146797316.-2207520000.1461010809./828564190588974/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.473361306109266.1073741842.399814146797316/767660176679376/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.754886164623444.1073741885.399814146797316/754886207956773/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.754886164623444.1073741885.399814146797316/754886294623431/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/a.754886164623444.1073741885.399814146797316/754886281290099/?type=3&theater
https://www.facebook.com/hanszenhistory/photos/pb.399814146797316.-2207520000.1461011823./818428881602505/?type=3&theater

SPACES
https://www.facebook.com/photo.php?fbid=1009966169083659&set=gm.1303640252983307&type=3&theater
https://www.facebook.com/photo.php?fbid=10208161724542709&set=g.365966220084053&type=1&theater
https://www.facebook.com/photo.php?fbid=10208161724262702&set=g.365966220084053&type=1&theater
https://www.facebook.com/photo.php?fbid=10154038336079512&set=g.365966220084053&type=1&theater
https://www.facebook.com/hanszencollege/photos/a.10150571307060810.373496.25745000809/10150571307080810/?type=3&theater

**Comment by jjbean97** [comment]
@pjgranahan

**Comment by pjgranahan** [comment]
I think everything that needed pictures, has pictures.
