### ISSUE TITLE
History

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#5]
This content needs to be gathered/created for the website.

The history of:
- [ ] Hanszen Traditions
- [ ] Hanszen Founder (Harry Clay Hanszen)

etc?

**Comment by Avery-Whitaker** [comment]
Just curious, but why don't we just reuse what was on the old website for things like this?

**Comment by pjgranahan** [comment]
I could have sworn that last time I checked, there were no archives of hanszen.rice.edu on the Wayback Machine, so it was a matter of necessity. However, I just checked and it looks like some of the text has survived: https://web.archive.org/web/20150808195716/http://hanszen.rice.edu/, so we certainly could reuse old content.

**Comment by Avery-Whitaker** [comment]
I took the liberty of downloading the entire Hanszen website archived there. (Wayback machine's web interface can be annoying to use)

I could upload it to a new repository if you'd like, although I don't think I can make new repos

**Comment by pjgranahan** [comment]
Sure, it can't hurt to have it preserved, even if we lost the CMS behind it. You should be able to make a new repo that's part of the Hanszen organization now.

**Comment by pjgranahan** [comment]
Added (by @kennygrosz ?)
