### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#7]
This content needs to be gathered/created for the website.

Hanszen's Crest in different sizes/colors/resolutions/formats

**Comment by kennygrosz** [comment]
Asking Andrew Elsey

**Comment by kennygrosz** [comment]
Andrew send me the Merch folder, which has a lot of different versions of the Hanszen crest-- it is attached
[merch.zip](https://github.com/hanszen/hanszen.github.io/files/224900/merch.zip)

**Comment by pjgranahan** [comment]
This is non-blocking. It's just something that would be nice to have eventually.

**Comment by kennygrosz** [comment]
You mean like a page with the "official" versions of the Hsnszen logo? That's a cool idea I know people are always looking for it

**Comment by pjgranahan** [comment]
Yeah, I've needed it multiple times. Ideally we'd have a single, canonical version of the crest available in a lossless format, and some versions available in different resolutions/formats.

**Comment by ase1** [comment]
I'll work on making a perfect SVG for general use. How do we want to format
the media page?

_Andrew Elsey_  |  Rice University Mechanical Engineering '17

**Comment by kennygrosz** [comment]
I'd say to strongly deprioritize this right now. Let's chat about it in a
week after the new student rush is over.

**Comment by ase1** [comment]
I agree. There's a bunch of resources that we should consider putting on
the page, long-term, though.

_Andrew Elsey_  |  Rice University Mechanical Engineering '17

**Comment by pjgranahan** [comment]
Agree with Kenny, this is lowest priority.
