### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by pjgranahan** [hanszen/hanszen.github.io#8]
This content needs to be gathered/created for the website.
- [x] Hanszen's mailing address
- [x] College Coordinator
- [x] H-Team

**Comment by kennygrosz** [comment]
Hanszen's Mailing Address:
Hanszen College
6350 Main Street
Houston, TX 77005

**Comment by kennygrosz** [comment]
College Coordinator
Joyce Bald
Hanszen College | Rice University	
6350 Main St, Houston TX 77005
Office: 713-348-4024 |Fax: 713-348-5963
joyce@rice.edu

**Comment by kennygrosz** [comment]
H-Team:

Masters:
Paul and Klaudia Brace | Masters
kbrace@rice.edu
pbrace@rice.edu

Danny and Diana Garcia | New Section RA's 
Danny: ddg3@rice.edu
Diana: dmgarcia@rice.edu

Alan and Rebecca Russell | Old Section RA's
Alan: agr2@rice.edu
Rebecca: russelr@rice.edu


Alan

**Comment by pjgranahan** [comment]
Should the RA and master info be on the contact page?

**Comment by pjgranahan** [comment]
@kennygrosz thoughts?

**Comment by kennygrosz** [comment]
it may make sense to just leave joyce, since she should be the point-person for hanszen stuff to external people and i think anyone in hanszen knows how to reach RA's (and their phone #'s shouldn't be up anyway). what do you think?

**Comment by pjgranahan** [comment]
I agree
